import { PropsWithChildren } from 'react'
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
		<AntdRegistry>
		  {children}
		</AntdRegistry>
	  </body>
    </html>
  );
}
